name: rovireq
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  # Storage using parquet
  - pyarrow

  # Storage using PostgreSQL
  - postgresql

  # Basics
  - pandas
  - matplotlib
  - numpy
  - requests
  - tqdm
  - jupyterlab

  - pip
  - pip:
    - papermill
    - psycopg[binary]
