name: rovireq
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  # Storage using parquet
  - pyarrow

  # Basics
  - pandas
  - matplotlib
  - numpy
  - requests
  - tqdm
  - jupyterlab
